app = "bold-field-6241"
primary_region = "atl"

[http_service]
  force_https = true
  processes = ["app"]
  internal_port = 3000
  min_machines_running = 0
  auto_stop_machines = true
  auto_start_machines = true
